---
volumes:
  prometheus-data:
    driver: local

services:
  prometheus:
    image: registry.hellnet.se/prom/prometheus:v2.49.1
    container_name: prometheus
    ports:
      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml --web.config.file=/etc/prometheus/web.yml"
    volumes:
      - prometheus-data:/prometheus
      - ./config:/etc/prometheus
    restart: unless-stopped
